### ISSUE TITLE
Retro for the Gatsby theme website building process

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#242]
> As an IBM.com library website creator with the Carbon Gastbt Theme, 

> I need a way to record all the things that work well, does not work well, during the website developing process

> so that I can share the findings with the Carbon Team and contribute to making the Carbon Gatsby Theme better.

#### Tasks

- [x] Set up a Gatsby Theme website development retro - Jeff, Wonil, Jacob, and Jenny.
- [x] Create a list of the retro items to share with the Carbon Team.

#### Acceptance criteria
- [ ] Share the outcome with the Carbon Team.

**Comment by JennySanchez** [comment]
**Items to be recorded from #191**

![Screen Shot 2019-12-20 at 3 09 56 PM](https://user-images.githubusercontent.com/45213839/71295451-820da480-2341-11ea-85ae-19311a2f273b.png)

**Comment by JennySanchez** [comment]
I reached out to Roberta for facilitating the retro session and she agreed - Thank you @roberta!👏 👏 👏 

The session scheduled for Thursday 02/19.
Trello board set up for the session can be viewed [here](https://trello.com/b/kl8YLD9d/gatsby-website-creation-process-retrospective0

**Comment by JennySanchez** [comment]
Gatsby website creation process retrospective session completed and follow up with the team via Slack. 

**Next step:** Jacob and I will meet and create issues for the action items as needed.

**Comment by JennySanchez** [comment]
task issues created for the action items:
[#1756](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/1756), https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/370, https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/371, https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/372, https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/373

![Screen Shot 2020-03-23 at 5 35 50 PM](https://user-images.githubusercontent.com/45213839/77369508-ccc9fe80-6d2c-11ea-8d9e-c98bad183e3b.png)
