### ISSUE TITLE
Create video for the Homepage

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#251]
> As an IBM.com library website creator

> I need to create a video

> so that our adopters can be visually engaged when they land on the homepage.

#### Additional information
 - This is an epic that links all of the stories needed to properly create and implement the video.

#### Tasks
- [ ]  Find out the proper format of the video for the Gatsby theme
- [ ]  Brainstorm the stories for the video
- [ ]  Shoot and edit the video
- [ ]  Get feedback and finalize the video
- [ ]  Implement the video (video player coding)

#### Acceptance criteria
- [ ]  The video is showcased in the homepage Lead Space area.
