### ISSUE TITLE
Homepage video creation - Shotting

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#253]
> As an IBM.com library website creator

> I need to create a video

> so that our adopters can be visually engaged when they land on the homepage.

#### Task
- [x]  Brainstorm the stories for the video
- [ ]  Shoot the video

#### Acceptance criteria
- [ ]  Have a video shoot and ready for review with the team.

**Comment by JennySanchez** [comment]
**Note:** Jeff mentioned we will use the same code Carbon has on the homepage and swap out the videos. The ones we need to swap out are the ones highlighted in pink.

![Screen Shot 2020-01-17 at 12 31 42 PM](https://user-images.githubusercontent.com/45213839/72636736-56241580-3925-11ea-8453-866499cf3855.png)

The link for us to download the videos is [here](https://github.com/carbon-design-system/carbon-website/tree/master/src/components/HomepageVideo).

**Comment by JennySanchez** [comment]
@wonilsuhibm Please let Roberta and I know which sprint we might be able to start the video shotting process. The video is for the v1.1 release update.
