### ISSUE TITLE
Homepage video creation - editing

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#254]
> As an IBM.com library website creator

> I need to create a video

> so that our adopters can be visually engaged when they land on the homepage.

#### Task
- [ ]  Edit the video
- [ ]  Get feedback and finalize the video

#### Acceptance criteria
- [ ]  Have a finalized video ready for coding implementation.
