### ISSUE TITLE
Pattern: demo component

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#267]
_Wonil-Suh1 created the following on Apr 11:_  

 ### User story
As a maker I need a way to preview a pattern, understand the grids, get specs, and grab code so that I can use it the right way.

### Notes
(Modify as needed)

- Anything task detail you can share?
- Any resource links or documents do you have?
- Any specific time period this task should be completed?
- Does this task relate to any other task issues?
- Does this affect anyone else?

### Acceptance criteria
(Modify as needed)

- [ ] Design approved
- [ ] Code approved
- [ ] Sprint demoed
- [ ] OM accepted
- [ ] Guideline published
- [ ] Content published

###  Tasks
(Modify as needed)

**For Content:**
- [ ] Project kick off (at least: dev, designer, and content creator)
- [ ] Create content draft
- [ ] Review draft with key users (get feedback)
- [ ] Work on content revision
- [ ] Finalize content
- [ ] Have final content aproved

**For Design:**
- [ ] Project kick off (at least: dev and designer)
- [ ] Work on wireframe/Ideation
- [ ] Create Initital design
- [ ] Review deisng with team memebers (get feedback)
- [ ] Work on design revision
- [ ] Finalize design
- [ ] Have final design aproved

**For Code:**
- [ ] Project kick off (at least: dev and designer)
- [ ] Write code
- [ ] Review code with team memebers (get feedback)
- [ ] Work on code revision
- [ ] Finalize Code
- [ ] Have final code review and designer QA
- [ ] Set up PR request
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/715_

**Comment by RobertaJHahn** [comment]
not stale
