### ISSUE TITLE
Finalize Cupcake website Layout Pattern/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#288]
In order to publish the latest Layout patterns overview page to the cupcake website we need approval of the content.

### Tasks

- [x] Get feedback on content from DDS members (Wonil, Olivia, Jenny)
- [x] Get feedback on content from DGC leadership (Elliott)
- [x] Get feedback on content from DGC squad designers
- [x] Update guidelines and visual assets based on feedback
- [x] Share with Jenny and Jacob for publishing to site

Layout patterns overview content **updates** were captured in this issue: https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/244

**Comment by larahanlon2** [comment]
Latest overview page 3.0.0 can be viewed [here](https://ibm.ent.box.com/notes/594294393853).

**Comment by larahanlon2** [comment]
Shared with DGC team during weekly critique, Tues Jan 21.
Questions from Elliott:

- Who is this for? Need to be clear on who will be/should be using these guidelines
- How does this get us closer to templates?
- Are we asking designers to _design_ or _adopt_ patterns?

**Comment by larahanlon2** [comment]
For further feedback and to understand some of our DGC adopters, I shared [this draft layout page](https://ibm.box.com/s/uwat3wojctvdpnxootcnzad49b6fvkv7) with Shixie (Checkout squad), Lila (TS), Jacob (DDS), and asked the following:


**1. In general, is this kind of guidance helpful to you? Why?
2. What was the most impactful or useful section?
3. Did the supporting illustrations make sense?
4. Were you confused about any of the sections / guidance / language?
5. Is there anything not here that you would like to see, in relation to Layout patterns?
6. Does the location of page (in the left nav) make sense or would you expect to find this information somewhere else?
7. Any other feedback would be great!**

**Comment by larahanlon2** [comment]
### Feedback from Lila (annotated InVision) [here](https://ibm.invisionapp.com/share/ANNZNCPS9YF#/319400725_Layout-Overview-Page-3-0-0--mockup-V1).

### Feedback from Jacob:

>  I love each of the sub section with clear examples. Love the idea of a gallery of layout patterns towards the bottom. I was confused about the purpose of the content, it is the purpose to help people understand how to design a new layout pattern or multiple patterns into a template? To me it feels like some content is focused on patterns themselves and other on the whole page. What is the Carbon productive workflow patterns link? I support adding the best practices of 2x grid to the guidelines page because it seems out of place on this page.
> 
> What if we structured the content in sections like "Designing a layout patterns" (show everything at the pattern level) and "Building pages with layout patterns" (show everything at the page level)?
> My only confusion with the "Carbon productive workflow patterns" is that when you visit the Carbon site they are just called "Patterns" so it could be confusing. I support changing the card title to "Carbon patterns." I wonder if we could work with them on eventually changing their patterns to "workflow patterns" because that naming makes more sense.

**Comment by JennySanchez** [comment]
@larahanlon2 Thank you for the follow-up meeting today. Can't wait to see the content go live on the Cupcake website. As discussed, we will work on the content update on the website in the next sprint (task issue #289).

**Comment by JennySanchez** [comment]
The next step task will be recorded via #289.

**Comment by larahanlon2** [comment]
The current iteration of content is ready to publish on cupcake site. Additional content and visuals will be added as we publish and get more feedback. https://ibm.ent.box.com/notes/594294393853

Closing.
