### ISSUE TITLE
Update the Layout Patterns/Overview Page content

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#289]
The latest content for Layout patterns overview page needs to be published on the cupcake site. It currently lives in Box: https://ibm.ent.box.com/notes/594294393853

## Tasks
- [x] Lara to share content with Jacob
- [x] Jacob to port content to Gatsby theme
- [x] Lara and Jacob to work together on image production, content styling etc.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc As discussed with Lara, we are ready to update the Layout Patterns/Overview Page with the content she has. Please start to migrate the content to the live website with the markdowns.

**Comment by JennySanchez** [comment]
FYI - @larahanlon2 This issue is for the content update on the website.

**Comment by jacobottesen-dgc** [comment]
Continuing to make updates. All content and images added. I still need to clean up the formatting of content. Lara will be reviewing it by EOD 02/05.

Live link here:
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/314/index.html

cc. @JennySanchez

**Comment by larahanlon2** [comment]
@jacobottesen-dgc hey, I just updated the description of this story and moved it to **done**. Let me know if you need to add anything else before end of sprint but any feedback we receive from this iteration we will add to the backlog for future updated.
