### ISSUE TITLE
 CTA guideline content - study and draft

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#301]
> As an IBM.com Library adopter
> I need a guideline to follow and effectively create the CTA label 
> so that I can not only do my day to day work without confusion but also support a better user experience on IBM.com.

### Notes
- We do not have a Voice and Tone guideline.
- We need to work with the Carbon team for this.
- Collen did some reach across the Modern Commerce to work on the CTA alignment. 
- The original issue about the CTA guideline creation can be viewed via the link below. (https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/197)

### Tasks
- [x] Set up a time to talk to Collen.
- [x] Conduct quick research on what we currently have in IBM, Marketing Team and Carbon.

#### Acceptance criteria
- [x] Have an action plan for the CTA Guideline creation.
- [x] Share the plan with Jenny and Wonil.
- [x] Create a new task issue for the guideline creation.

**Comment by JennySanchez** [comment]
@wonilsuhibm FYI on this task existed.

**Comment by jimpistilli** [comment]
Call scheduled with Colleen and Jenny Weds 2/5.

**Comment by jimpistilli** [comment]
Call that was scheduled for 2/5 to discuss existing CTA research was cancelled due to research not relevant. Jim working on conducting external research and will provide a draft by 2/5 instead. 

cc: @JennySanchez

**Comment by jimpistilli** [comment]
Put up a draft on Box located at: https://ibm.box.com/s/19u2nol7bogxbfay8y80pawizp3vjf2f

cc: @JennySanchez @wonilsuhibm

**Comment by JennySanchez** [comment]
@jimpistilli I made comments and please feel free to let me know if the comments make sense to you.

**Comment by jimpistilli** [comment]
@JennySanchez Updated to reflect your comments

cc: @wonilsuhibm

**Comment by jimpistilli** [comment]
@wonilsuhibm Current draft here: https://ibm.box.com/s/19u2nol7bogxbfay8y80pawizp3vjf2f

**Comment by wonilsuhibm** [comment]
@jimpistilli @JennySanchez THank you. I feel that this guideline should also touch upon the placement of CTAs on a page, number of CTAs on a page, its relationship with the overall narrative on the page.

**Comment by JennySanchez** [comment]
@wonilsuhibm Agreed with you, we are focusing on the Label for this week. Below is what I think we should include in a CTA guideline page. The goal of this guideline is to help IBM.com creator understand what is CTA and how they can create an impactful CTA. I quickly add some ideas but it's up to @jimpistilli 's finding and his recommendation. Please also add any ideas or thoughts you have to help us get started on the guideline creation.


**What is a CTA?**
(purpose and components of a CTA)

**Why CTA is important?**

**Format (best practices)** 
Idea: When to use a text link, button, etc for CTA?

**Label/Microcopy (best practices)** 
Idea: wording, length, size, first-person speech style? 

**Color (best practices)**

**Placement/Location (best practices)**
Idea: Where should a CTA locate in a banner, a form, and a website page?
Idea: How a proper white space around the CTA can help the CTA stand out?
Idea: What to do when a CTA needs to be on top of an image?
Idea: How to ensure the CTA works well even in responsive design.

**Other tips on crafting an effective CTA**
Idea: Keep the CTA label consistent across the user experience flow.
Idea: Test your CTA with the target users to improve the CTA. Monitor the click-through rate?

**Comment by jimpistilli** [comment]
@JennySanchez I have some other research that answers most of these questions that I came across while doing the label research. Let me review and think about how to best group answering your questions, keeping it brief as @wonilsuhibm likes, but also is informative enough for a reader.

**Comment by jimpistilli** [comment]
@wonilsuhibm Below is a new version hopefully addressing your questions. Also please note I put a couple of questions in the comments, as I'm not totally sure where is the line between what we define for CTA appearances and leave it to the adopter to create.

https://ibm.ent.box.com/file/611831869280

cc: @JennySanchez

**Comment by JennySanchez** [comment]
@jimpistilli I added a few comments to your document.

**Comment by jimpistilli** [comment]
@JennySanchez New version below that addresses your comments. Will stand by for any other edits

https://ibm.ent.box.com/file/611831869280

cc: @wonilsuhibm

**Comment by JennySanchez** [comment]
Next step: #328.
