### ISSUE TITLE
Finalize CTA Guideline copy

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#328]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively create the CTA for my day-to-day work

> so that I can not only do my day to day work without confusion but also support a better user experience on IBM.com.

### Tasks
- [ ] Get feedback from team members
- [ ] Jim to review CTA Guideline (#301) with Wonil 

#### Acceptance criteria
- [ ] Copy is finalized, approved by Wonil and ready for Jenny to work on the design (#341).

**Comment by jimpistilli** [comment]
Adding most recent version of CTA guideline copy here awaiting review:

https://ibm.box.com/s/19u2nol7bogxbfay8y80pawizp3vjf2f

@wonilsuhibm @JennySanchez

**Comment by jimpistilli** [comment]
@JennySanchez Hi - some of the screen captures are not a high enough resolution for me to read all of the text, there are portions that are too small / blurry. Is there a way to send better quality versions? Thanks 

cc: @wonilsuhibm

**Comment by JennySanchez** [comment]
@jimpistilli I looked over the guidelines with James and Jacob to gather feedback and there are a few more things to share with you. Let me know if the feedback helps and if you have any questions.

---
(Intro)
The CTA alone should not be used to persuade users but rather the supporting content. The CTA is more of a navigation or guiding component so I am not sure if we should use the word "persuading" in the first sentence?

(Placement)
The "fold" does not really exist and we do not have any guidelines around the fold, so maybe not use it or mention it?

(Size, Shape, and Color)
Since we have the button component and already standards for the adopters to follow and use, do we need color, shape, and size sections? 

For this reason, we might not want to encourage the adopters experimenting with various colors, sizes, and shapes.

(Quantity and Labels)
I have seen people use the word "Label" to describe the text on the button, but I am also not sure if we should call the CTA text as "labels"? Should we use "button copy" or "button text" instead of the "label"? Is there an industry standardized term for it? or What is the IBM standard on calling it? 

I found this article and there is more detail for your reference - [5 Rules for Choosing the Right Words on Button Labels](https://uxmovement.com/buttons/5-rules-for-choosing-the-right-words-on-button-labels/).

---

I am not sure if we should address something around accessibility?

For example, Screen readers handle links slightly differently than they do buttons. All links and buttons are tab-able, but pressing the Space key or Enter triggers a button, whereas pressing the Enter key only triggers a link.

I found this article and there is more detail for your reference - [Links, Buttons, & Other Clickable Elements](http://web-accessibility.carnegiemuseums.org/content/buttons/).

**Comment by jimpistilli** [comment]
Hey @JennySanchez, individual comments / questions below:

Sure, no problem
_(Intro)
The CTA alone should not be used to persuade users but rather the supporting content. The CTA is more of a navigation or guiding component so I am not sure if we should use the word "persuading" in the first sentence?_

OK
_(Placement)
The "fold" does not really exist and we do not have any guidelines around the fold, so maybe not use it or mention it?_

I asked the same question before I added copy for each. @wonilsuhibm deferred to you, so I am not sure as there is conflicting messages on whether this copy should be there or not.
_(Size, Shape, and Color)
Since we have the button component and already standards for the adopters to follow and use, do we need color, shape, and size sections?_
_For this reason, we might not want to encourage the adopters experimenting with various colors, sizes, and shapes._

I thought we agreed on calling the copy a "label" - I can explain it a little more specifically that CTA button copy is called a label, but I thought we agreed on using label as the terminology.
_(Quantity and Labels)
I have seen people use the word "Label" to describe the text on the button, but I am also not sure if we should call the CTA text as "labels"? Should we use "button copy" or "button text" instead of the "label"? Is there an industry standardized term for it? or What is the IBM standard on calling it?_
_I found this article and there is more detail for your reference - 5 Rules for Choosing the Right Words on Button Labels._

This would be the first I heard about adding accessibility text, I can, but want to confirm you want it there. 
_For example, Screen readers handle links slightly differently than they do buttons. All links and buttons are tab-able, but pressing the Space key or Enter triggers a button, whereas pressing the Enter key only triggers a link._

Also not sure if @wonilsuhibm has any thoughts to add.  Thanks

**Comment by JennySanchez** [comment]
@jimpistilli For accessibility, I am not sure what is accessibility text? What I meant is if we should add anything that might be the best practices around the CTA buttons or links accessibility? We do not have to, but just a thought.

**Comment by jimpistilli** [comment]
@JennySanchez Re: Accessibility, well what is the precedent established for including accessibility information in other similar applications like this? Is that something you typically touch on?

Information taken from that site below that was mentioned, accessibility text can be things like including information about using the keyboard to navigate, designating certain colors to never be used, there really are a host of things we could touch on with accessibility in mind.

https://w3.ibm.com/able/devtest/quick/design.html

cc: @wonilsuhibm 
https://w3.ibm.com/able/devtest/quick/design.html

**Comment by wonilsuhibm** [comment]
Thankyou @JennySanchez and @jimpistilli 

### Placement
The whole above-the-fold business really depends on the type of content—some pages may not even have a primary CTA until much later, below the fold.

I'm also wondering if we could touch upon the relation between the content and CTAs—something along the line of "make sure to place CTAs where it makes sense from the content structure on the page instead of peppering CTAs all over the page".

### Size, color, shape
Let's not mention any experimentation—we have very well defined buttons, there should be no experimentation with these attributes.

### Quantity
Is this section necessary, since it really depends on the content? Maybe the placement section can touch upon not having too many CTAs to overwhelm the user.

### Different types of CTAs
Should we touch upon the different types fo CTAs—primary, secondary, etc?

### Other potential topics to cover
- misleading CTAs
- leading users off the page too early
- leading the user off the page without a proper linking strategy

**Comment by jimpistilli** [comment]
@wonilsuhibm Thanks for clarifying, will return an updated version shortly.

cc: @JennySanchez

**Comment by JennySanchez** [comment]
@jimpistilli  I agreed with Wonil's feedback. For the different types of CTAs—primary, secondary, etc. Please make sure we have a link that can be linked to the [button components page](https://www.carbondesignsystem.com/components/button/code/) so the adopters can learn more about the buttons.

**Comment by jimpistilli** [comment]
@JennySanchez New version below:

https://ibm.box.com/s/19u2nol7bogxbfay8y80pawizp3vjf2f

cc: @wonilsuhibm

**Comment by JennySanchez** [comment]
@wonilsuhibm Anything else to add before we publishing it on the website for now and get feedback from the adopters?
