### ISSUE TITLE
Idea: Collect images from the IBM.com teams for the 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#333]
> As an IBM.com library website creator,

> I need a way to select the works from the IBM.com teams

> So that I can use the images for website content creation.

#### Tasks
- [ ] Create a BOX folder for the collection
- [ ] Communicate to all teams on what type of images we are collecting

#### Acceptance criteria
- [ ] IBM.com designers know where to drop the images

**Comment by JennySanchez** [comment]
@wonilsuhibm Let me know what do you think?

**Comment by JennySanchez** [comment]
Note: This task can somewhat linked to #1391
