### ISSUE TITLE
Finalize and publish the MVP version CTA Guideline page content to the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#340]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively create the CTA for my day-to-day work

> so that I can not only do my day to day work without confusion but also support a better user experience on IBM.com.

### Tasks
- [x] Review the latest CTA Guideline with Wonil and Reboot Content Strategist for input on the edits.
- [x] Finalize the content on the website via markdowns or code based on the design (#340)

#### Acceptance criteria
- [x] Content is published and live on the website.
- [x] Make the announcement on Slack for the adopters.

**Comment by JennySanchez** [comment]
We have adopter asking about the CTA best practices and we should take a look at this task so we can finalize the content and publish the content with proper priority set up.

https://cognitive-app.slack.com/archives/GBG66T9NK/p1597064143000200

![Screen Shot 2020-08-10 at 1 12 23 PM](https://user-images.githubusercontent.com/45213839/89815879-26c83680-db0b-11ea-8a72-6bc0fd6f1930.png)

**Comment by JennySanchez** [comment]
**Note:**

_The steps we took and the work we did in the past to get to where we at right now_

1. CTA guideline content - study and draft task issue can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/301).

2. Finalize CTA Guideline copy task issue can be viewed https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/328.

3. Content edit for the CTA Guideline/Placement section task issue can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/353). The finalized content from Jim can be viewed in this [BOX document](https://ibm.box.com/s/19u2nol7bogxbfay8y80pawizp3vjf2f).

4. The task issue for the design can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/341).

5. The task to review the current CTA Guideline Content with Jill and make a plan for the content update can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/356)

**Comment by JennySanchez** [comment]
We have one more adopter asking for CTA best practices on Slack.
![Screen Shot 2020-08-26 at 8 03 46 AM](https://user-images.githubusercontent.com/45213839/91307008-02a75f00-e773-11ea-802d-71358acb0ed2.png)

**Comment by wonilsuhibm** [comment]
@JennySanchez The guideline content was edited and updated by Tina and me here: https://ibm.box.com/s/gntiojojxqkpjyeo7hwt7gf25azbuc0s

Please take a look and let me know if this makes sense.

**Comment by JennySanchez** [comment]
@wonilsuhibm The edits look good. The only thing is to me is we should take the last sentence in the "Summary" section (see below) off since this is the CTA guidance we provide to our adopters.

"For more information on CTA guidance, style and code, please visit here. [Add another reference here, if available]"

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Once Wonil confirmed we are good to go, we can start working on the page with markdowns.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez @wonilsuhibm 

CTA guideline content has been published and merge live to the site.
