### ISSUE TITLE
Design the CTA Guideline page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#341]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively create the CTA for my day-to-day work

> so that I can not only do my day to day work without confusion but also support a better user experience on IBM.com.

### Tasks
- [x] Design the page with finalized content
- [x] Craft the Dos and Don'ts examples.

#### Acceptance criteria
- [x] Design is ready and accepted by Wonil.

**Comment by JennySanchez** [comment]
**Task update:**
The initial design is in work progress and needs content edits. Jim is working on the edit via issue #353 

![CTA Guideline v3 - reference](https://user-images.githubusercontent.com/45213839/75817572-f6f75480-5d5c-11ea-8255-39a85696924e.jpg)

**Comment by JennySanchez** [comment]
Placement section content updated.

![CTA Guideline v3 - with updated content.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/f55b5059-c368-4c41-aa7a-79318e0baeab)

---

@larahanlon2 @wonilsuhibm Can you take a look and let me know what do you think? Thank you.

**Comment by wonilsuhibm** [comment]
@JennySanchez The design looks good to me, but I have a few concerns regarding the content. Where are we with the content?

**Comment by JennySanchez** [comment]
@wonilsuhibm The content in the design above is the latest. The detail of Jim's work can be viewed via #328.

**Comment by JennySanchez** [comment]
**Note:** We have additional edits on the content - task issue #356 created for the work.
