### ISSUE TITLE
Finalize Cupcake website Homepage design

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#352]
#### User story
> As an IBM.com Library adopter, 

> I need to go to a website to get guidelines and resources  I need for my work without confusion 

> so that I can find the information I need with confidence.

#### Tasks
- [ ] Work on the homepage design revisions based on the feedback received from the designers. See #326 for detail.

#### Acceptance criteria
- [ ] Design is finalized and ready to be estimated by James

**Comment by JennySanchez** [comment]
**Task update:**
Shared the designs with Mike and scheduled the time to walk him through the designs to get feedback.

**Comment by JennySanchez** [comment]
Got feedback via Slack from Mike and made some updates (see below). He can not make it last Friday so the review was rescheduled for tomorrow.

![Style B 03 - 1x.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/5052585b-93f0-4e03-85ab-1b24f5282999)

**Comment by JennySanchez** [comment]
@wonilsuhibm Let me know what do you think.

Below are the purposed design with three different background treatments based on our discussion today. I prefer v5-01 or v5-03. 
![Screen Shot 2020-03-16 at 4 09 49 PM](https://user-images.githubusercontent.com/45213839/76800010-ba861880-67a0-11ea-93fe-604e11ec94df.png)

For the hero message, I add a break/space below "Imagine" to see if it works better and I think it works better for the reading experience and matches "get started." and "Contribute" better. 
![Screen Shot 2020-03-16 at 4 10 19 PM](https://user-images.githubusercontent.com/45213839/76800096-e99c8a00-67a0-11ea-988c-c6dbf16061ce.png)

**Comment by JennySanchez** [comment]
**Feedback from Mike:**
![Screen Shot 2020-03-17 at 4 11 24 PM](https://user-images.githubusercontent.com/45213839/76904110-50877500-686d-11ea-8d6d-d24de5f0bf72.png)

**Comment by JennySanchez** [comment]
@wonilsuhibm The iterations based v05-01 are ready for you to take a look and let me know what do you think.

Mike's feedback:

- [ ] The type size for the hero section seems too large.
- [ ] The type size for the "Get started" and "Contribute" seems too large and when we use the large type, it’s better to use "light".
- [ ] The hero copy is written as though we're a marketing site but we are not, like “Imagine.” is too fluffy. `We might want to work on the copy with Jill`.

For comparison purpose:

(The v05-01)
![v5 - 01](https://user-images.githubusercontent.com/45213839/77365542-4f9a8b80-6d24-11ea-8934-2df22be460b0.jpg)


(The iterations v06-01, v06-02, v06-02 with v6 - 02 with section titles in medium, and v06-03)
![Screen Shot 2020-03-23 at 4 37 40 PM](https://user-images.githubusercontent.com/45213839/77365748-a43e0680-6d24-11ea-8e29-f9840bf1d694.png)

**Sketch work file:** 
[IBM.com Library-Homepage_design-03232020.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/4372023/IBM.com.Library-Homepage_design-03232020.zip)

**Comment by JennySanchez** [comment]
@wonilsuhibm Below is the updated design with the hero message in (A) eight-column width and (B) ten-column width as discussed.

👉 Sketch work file is saved in the [BOX folder](https://ibm.box.com/s/iowwmm7m0ygzqmc35ykenwzyue9ivotn).

(A) 
![v7- with hero message in eight-column width](https://user-images.githubusercontent.com/45213839/77696225-03955400-6f7b-11ea-8804-53e6960f2592.jpg)

(B)
![v7- with hero message in ten-column width](https://user-images.githubusercontent.com/45213839/77696240-08f29e80-6f7b-11ea-8180-57770661f88a.jpg)
