### ISSUE TITLE
Review the current CTA Guideline Content with Jill and make a plan for the content update

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#356]
> As an IBM.com Library adopter

> I need a guideline to follow and effectively create the CTA for my day-to-day work

> so that I can not only do my day to day work without confusion but also support a better user experience on IBM.com.

### Tasks
- [ ] Review the content with Jill and Wonil.
- [ ] Update the design (#341) with the updated content.

#### Acceptance criteria
- [ ] Design is updated and ready for publishing.

**Comment by JennySanchez** [comment]
Jill is out of the office next week. The review meeting is scheduled for 03/24 (Tuesday).

**Comment by JennySanchez** [comment]
**Content and design for review:**
![CTA Guideline v4](https://user-images.githubusercontent.com/45213839/76792406-ffa24e80-6790-11ea-9c7a-16c81dfab32e.jpg)

**Comment by JennySanchez** [comment]
Jill is on a higher priority project and will not be able to collaborate on this task for now. Based on the conversation I had with @wonilsuhibm  we will move this task to the "Backlog" for now.

FYI - @RobertaJHahn
