### ISSUE TITLE
Create inspiration library for IBM.com designers on website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#358]
> As an IBM.com library adopter,

> I need a way to see the work from other IBM.com designers

> So that I can see actual examples for inspiration.

#### Tasks
- [ ] Design research on how other design systems and teams handle the inspiration library.
- [ ] Define what information needs to be included
- [ ] Craft the experience with a prototype for testing
- [ ] Work on the design
- [ ] Code the finalized design
- [ ] Publish the content and implement the library on the website.

#### Acceptance criteria
Inspiration library lives on the website and shared with the IBM.com teams.

#### Next step:
- [ ] Epic is reviewed and prioritized for creating sub-issues for execution.
