### ISSUE TITLE
Update the Homepage "hero" and "Start designing" images

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#360]
> As an IBM.com Library website creator, 

> I need to create images with perper size and resolution to be displayed

> so that the images are displayed properly.

#### Additional information

The current homepage "hero" and "Start designing" images look blurry and low res.
![Screen Shot 2020-03-17 at 10.13.57 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/7bad886b-2226-49f3-b445-e08e441162fa)

#### Tasks
- [x] Images created based on the finding of #258.
- [x] Kenny test out the images
- [x] new images are reviewed and approved by Wonil

#### Acceptance criteria
- [x] Images updated on the live website.

**Comment by JennySanchez** [comment]
@wonilsuhibm Images on the homepage are updated and the preview for you to take a look is [here](https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/361/index.html).

Mike's concern is the images are too blurry or looks low res. For the "hero" image, we adjusted the mask filter to brought the detail out. For the "Start designing" image, we recreated the image and exported it with different settings and it works now.

---

**Left:** Updated images/**Right:** what we have on the website now.

![Screen Shot 2020-03-17 small at 2.55.22 PM.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/8222de46-b7ce-4531-8568-344b186988b8)

![Screen Shot 2020-03-17 at 2.54.34 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/295c3f6c-1816-4300-8637-adb9ae046fed)

**Comment by wonilsuhibm** [comment]
Looks great. Thank you.

One thing: the very dark parts of the image—can we make them slightly lighter so that it doesn't interact with the rest of the site?

<img width="1111" alt="Screen Shot 2020-03-26 at 2 25 44 PM" src="https://user-images.githubusercontent.com/30183447/77682735-cc6c7600-6f6d-11ea-8bbb-4f8444abbaf8.png">

**Comment by JennySanchez** [comment]
@kennylam Below is the edited image. Can you swap out the image for us?
PSD. Work file is attached as well, in case you need it. Thank you.

![ibm-dotcom-sticker-03_26](https://user-images.githubusercontent.com/45213839/77692104-050f4e00-6f74-11ea-95b3-ca007310e542.jpg)

[ibm-dotcom-sticker-March_26-Kenny.psd.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/4389717/ibm-dotcom-sticker-March_26-Kenny.psd.zip)

**Comment by JennySanchez** [comment]
Update completed. 

Deploy preview created:
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/361/index.html
