### ISSUE TITLE
Update intro styling for the Get started/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#363]
> As an IBM.com Library adopter, 

> I need a way to see the critical information right away,

> So that I won't miss an important piece of information.

#### Task

- [x] Do a quick research on how Carbon website treatment the content in the same category
- [x] Make update on the Get started/[Overview page](https://ibm-dotcom-library.mybluemix.net/getting-started).

#### Acceptance criteria
- [ ] Content treatment is updated and accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
**Note:** I noticed the vertical spacing below the section title is off again, I will take a look and make the fix as well.

@jacobottesen-dgc FYI, no need to do anything.

**Comment by JennySanchez** [comment]
**Update completed.** 

![Screen Shot 2020-03-19 at 3 44 23 PM](https://user-images.githubusercontent.com/45213839/77113433-cff57f80-69f8-11ea-8e20-d371784c566d.png)

---

@kennylam Do you know why the blue info icon is not showing up like what Carbon has (see below)?

![Screen Shot 2020-03-19 at 3 50 03 PM](https://user-images.githubusercontent.com/45213839/77113741-58742000-69f9-11ea-9aaf-ab69bba86d53.png)


I used the same markdowns they have but different messages, FYI.

<InlineNotification>

**Note:** Please direct all questions regarding support, bug fixes, and feature requests to the [Carbon Charts core team](https://github.com/carbon-design-system/carbon-charts#core-team).

</InlineNotification>

**Comment by kennylam** [comment]
@JennySanchez looks like this icon is available in an alpha of the `gatsby-theme-carbon` package. I suggest holding off on upgrading until a stable release is available.

**Comment by JennySanchez** [comment]
@kennylam Got it and thank you for taking a look.

**Comment by wonilsuhibm** [comment]
Looks good to me. Thank you.
