### ISSUE TITLE
Update the website Roadmap information or links

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#365]
> As a Cupcake website creator

> I need to know what components, layout patterns, etc will be created or published on the cupcake website 

> so that I can have a discussion or make a plan for adoption with my team.use 

#### Task
- [x] Export the roadmap from Linda's PPT file to an acceptable file format for the website or Git wiki page.
- [x] Update the images and the links (if needed).

#### Acceptance criteria
- [x] Roadmap images or information is up to date on the website

**Comment by JennySanchez** [comment]
Images for the updates:

![Slide1](https://user-images.githubusercontent.com/45213839/77102236-82701700-69e6-11ea-816e-163cda69200e.jpeg)
![Slide2](https://user-images.githubusercontent.com/45213839/77102238-8308ad80-69e6-11ea-9105-e53ff1eeb2b5.jpeg)

**Comment by JennySanchez** [comment]
Roadmap page update completed.
