### ISSUE TITLE
Revisit how we can have IBM.com Library information from the Carbon website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#367]
> As a NEW IBM.com Library adopter,

> I need a way to get to the IBM.com Library website from the Carbon website, 

> So that I can tell the differences or relationships between the Carbon and IBM.com Libray without confusion.

#### Task
- [ ] Review the adopter pain point around getting confused between the two design system websites.
- [ ] Ideate and come up with proposals on how we can surface the IBM.com Library link on the Carbon homepage and other critical pages such as Resource Page.

#### Acceptance criteria
- [ ] Have a proposal for us to open a Git issue on Carbon's repo.
- [ ] Create the Git issue on Carbon's repo

**Comment by JennySanchez** [comment]
@wonilsuhibm It's my understanding you had a few conversations with Mike and the Carbon Team around the linking strategy (Short Term) between the IBM.com Library and Carbon websites. Can you share the latest discussion highlight here?

**Comment by JennySanchez** [comment]
Mike set up a regular bi-weekly meeting for the website linking discussion. 

The focus area will be as the following:
1. — About pages (explain Carbon system landscape clearly in both Carb/IBM.com and IDL)
2. — Left nav / IA between two sites. What stays unique, what can merge, and what is mirrored. etc.
3. — Home pages for each
4. — Naming for a top nav solution (e.g. Product design | Website design )

Based on the discussion Wonil, Linda, and I had earlier today, we are aligned on the directions and will start by looking at the navigation differences to facilitate the discussion next week. For now, this task issue will be moved to the ideation board and the continuous discussion detail will be recorded here. When we have a list of action items for the interim solution, individual task issues will be created on the Agile board for execution.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/digital-design-ideation #148](https://github.com/carbon-design-system/digital-design-ideation/issues/148) via [**ZenHub**](https://www.zenhub.com/)
