### ISSUE TITLE
Visit the Cupcake website roadmap and decided what we need to add to the website for MVP

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#370]
(Task created as one of the action items from the Gatsby Theme website building process retro #242).

> As an IBM.com Library website creator,

> I need to take a look of the Cupcake website roadmap with the product owner,

> so that I  know what we are going to work on as the 2020 MVPs.

#### Task
- [x] Schedule a time to go over the roadmap with Linda and Wonil.
- [x] Create task issue to finalize the MVP list/To-Be sitemap if needed

#### Acceptance criteria
- [x] Review the purposed MVP items with Linda and Wonil.

**Comment by JennySanchez** [comment]
Discussion session scheduled for April 08 (Wednesday) 1:00 pm CST.

**Comment by JennySanchez** [comment]
Went over the Mural.ly ideation and WIP To-Be sitemap with Wonil and Linda. The work to do follow up with Linda and update the To-Be sitemap will be captured via #387 .
