### ISSUE TITLE
Planning for create website artwork and visual reference guideline

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#371]
(Task created as one of the action items from the Gatsby Theme website building process retro #242).

> As an IBM.com Library team members,

> I need to follow a guideline when creating a visual reference for the website content

> so that I can create and provide the right assets.

#### Task
- [ ] Do research around what visual references we have on the website.
- [ ] Decided what we need to include in the guideline.

#### Acceptance criteria
- [ ] Have a list of what we are going to include in the guideline.
- [ ] Create a task issue/issues for guideline creation.

Note: Get Kenny or Jeff involved in the task can ensure we cover the dev requirements as well.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/digital-design-ideation #61](https://github.com/carbon-design-system/digital-design-ideation/issues/61) via [**ZenHub**](https://www.zenhub.com/)
