### ISSUE TITLE
Planning for Pattern ontology content publishing on the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#372]
(Task created as one of the action items from the Gatsby Theme website building process retro #242).

> As an IBM.com Library adopter,

> I need to understand how the pattern ontology works,

> so that I can create with confidence.

#### Task
- [ ] Discuss what we should provide to our adopters around the ontology work.
- [ ] Decided what we need to publish.

#### Acceptance criteria
- [ ] Have a clear idea of what we are going to include in the ontology education section or page.
- [ ] Create a task issue/issues for content creation.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/digital-design-ideation #60](https://github.com/carbon-design-system/digital-design-ideation/issues/60) via [**ZenHub**](https://www.zenhub.com/)
