### ISSUE TITLE
Website task prioritization with stream leads

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#374]
> As an IBM.com Library website creator,

> I need to take a look of the Cupcake website sitemap with the stream leads

> so that I know what we are going to work on as the 2020 MVPs.

#### Task
- [x] Schedule a time to go over the list of ideas and needs with Lara, Olivia, and Wonil.
- [x] Update the [Mural.ly board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94).

#### Acceptance criteria
- [x] Have a updated sitemap for roadmap discussion with Linda.

**Comment by JennySanchez** [comment]
I went over the To-Be sitemap with Wonil and Olivia. Priority for the Components and Guideline sections are added.

**Next step:** Catch up with Lara.

**Comment by JennySanchez** [comment]
Followed up with Lara today. Once the priority for the Layout pattern is done, I will close this task and move forward with the #370.

**Comment by JennySanchez** [comment]
Priority set up completed and ready to review the To-Be sitemap with Linda and Wonil - #370.
