### ISSUE TITLE
Website content audit for April 24th release

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#377]
> As an IBM.com library website creator, 

> I need to review the current content with stream leads and make content (copy, images, and links) updates if needed,

> so that we can release the website on April 24th (end of Sprint 20-08).

#### Information:
Based on the conversation I had with @ljcarot  today, we will shoot for April 24th as the website release date.

#### Task:

- [x] Review the content on the website with stream leads.
- [x] Make proper updates as needed.

#### Acceptance criteria
- [x] All content is up-to-day on the website.

**Comment by JennySanchez** [comment]
@ljcarot @jeffchew @wonilsuhibm I am not sure what would be the best way for us to collaborate on this task, but I am creating a to-do list or Git issues if needed for me to make the update or have a discussion with you all, FYI.

**Comment by JennySanchez** [comment]
@ljcarot @jeffchew @wonilsuhibm @jacobottesen-dgc 

👉 [April 24th release audit BOX doc](https://ibm.box.com/s/fgizf8lp8vyo4jszpt8o3g7mq5k9akyu) is created, please feel free to add anything to the document.

**Comment by JennySanchez** [comment]
Content updates completed and task issues created for the post-release update as needed.
