### ISSUE TITLE
Homepage current and white theme design comparison study

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#380]
> As an IBM.com Library website developer,

> I need a way to see the differences between the current homepage and the new design,

> so that I know what I am looking at when sizing.

#### Task
- [x] Mark the differences between the current homepage and the new design.
- [x] Add additional links to similar featured used in other Gatsby website s within the IDL eco-system.

#### Acceptance criteria
- [x] Have a marked document ready to share with the developer.

**Comment by JennySanchez** [comment]
**FYI on the task issue created:** @jeffchew @kennylam @wonilsuhibm @ljcarot @RobertaJHahn

**Comment by JennySanchez** [comment]
@wonilsuhibm @jeffchew Here's the homepage redesign comparison study to share with the Dev. team to assist the development work (task issue 381, 382, 383, 384, and 385) planning as discussed.

Please let me know who might be the person I need to collaborate with so I can walk the person through what's in this study and provide further guidance if needed.

[Homepage Redesign Comparison Study](https://user-images.githubusercontent.com/45213839/79917267-c85a3980-83ef-11ea-9eb5-a8b3eea78387.jpg)

**Comment by JennySanchez** [comment]
Task issue #381 created for the next step.
