### ISSUE TITLE
 Gatsby homepage code review for the new white theme design - Other resources section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#383]
> As an IBM.com Library website developer,

> I need a way to see if the new white theme homepage leads pace/hero image design is doable or not

> so that I can do sizing and set priority for the actual work to be started

![Other resources area.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/b58994f5-99ec-40a7-919b-f09c6d061e29)

#### Task
- [ ] Take a look at the Gasby theme homepage code and see if the new design can be done.
- [ ] Provide a list of the items a developer will need to do to get the task done (as needed).
- [ ] Provide an estimate of how many story point this task needs to have the new design go live on the website.

#### Acceptance criteria
- [ ] Story points ready and able to create a new task issue for the dev work to be started.

**Comment by JennySanchez** [comment]
**FYI on the task issue created:** @jeffchew @kennylam @wonilsuhibm @ljcarot @RobertaJHahn
