### ISSUE TITLE
Add The black transparent overlay and dotted grid to our homepage

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#386]
#### Feedback from Mike:
- The hero image is too bright and the black transparent overlay is missing.
- The dotted grid is missing.

(Carbon homepage hero image)
![Screen Shot 2020-04-07 at 9.18.07 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/94722fa5-f5e9-4c56-b905-50f153764434)
(IBM.com Library homepage hero image)
![Screen Shot 2020-04-07 at 9.18.17 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/49fa4db5-3fc3-4421-b151-4982d8364aea)

#### Note: 
After taking a look with Wonil, we think the dotted grid is in code. The black transparent overlay might be in code as well. 
We need a developer taking a look so we know how to add the overlay and dotted grid to the homepage.

#### Tasks
- [x] Take a look at the Gatsby code to find out if the black transparent overlay and dotted grid came with the Gatsby theme. 
- [ ] Work with Jenny on the updates.

#### Acceptance criteria
- [ ] The black transparent overlay and dotted grid are added to the live website.

**Comment by JennySanchez** [comment]
I talked to Kenny and we have a pretty good idea on how to make the changes. A work session will be scheduled for Sprint 20-08 for us to work on the task together.

FYI - @wonilsuhibm

**Comment by JennySanchez** [comment]
@kennylam Images attached.
![ibm-dotcom-sticker-April_06](https://user-images.githubusercontent.com/45213839/78692083-ffdcc800-78be-11ea-92cf-7938426a3c7a.jpg)

**Comment by JennySanchez** [comment]
@wonilsuhibm 

Deploy preview created:
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/407/index.html

Please let Kenny and I know if there are additional edits needed for this task.
