### ISSUE TITLE
Update Layout Pattern overview page/Layout patterns table list

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#388]
> As an IBM.com Library website creator, 

> I need to update the Layout patterns table list with the correct information

> so that the adopters won't be confused.

#### Additional information

The current homepage Layout patterns table list is not up to date.
![Screen Shot 2020-04-10 at 1.43.24 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/eb4abf03-1a85-40b0-a2b8-58ff4df9fa9f)

#### Tasks
- [ ] Work with Lara on the pattern naming list.
- [ ] Update the list with markdowns.

#### Acceptance criteria
- [ ] Table list is updated on the live website.

**Comment by JennySanchez** [comment]
Based on the Slack conversation I had with Lara, we will...

**1.** Update the list and update the status to "Stable", we do not use the word "Available" for ability so we can be aligned with the Carbon set up.

- Card section - Stable
- Content block- Stable
- Content group- Stable
- Feature card - Stable
- Lead space - Stable

**2.** We will a Resource section below the Pattern Layout List with a card so we can link it to the [Storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-get-started--read-me).

**Comment by JennySanchez** [comment]
Updates listed above are completed and can be viewed [here](https://ibm-dotcom-library.mybluemix.net/patterns).

**Comment by JennySanchez** [comment]
Section titles are updated as well based on the conversation with Lara.

Typographic structure/detailing to **Typographic structure**.
Enhanced reading/editorial/storytelling (wip title) to R**eading behaviors**.

**Comment by JennySanchez** [comment]
@larahanlon2 As discussed, let's add the pattern descriptions and individual storybook link to the overview table as the next step.

**Comment by larahanlon2** [comment]
Hey @JennySanchez [here ](https://ibm.ent.box.com/notes/656709988448)are the descriptions to add to the layout status table.

**Comment by JennySanchez** [comment]
@larahanlon2 The Layout Pattern list updates completed. Thank you for your help!
