### ISSUE TITLE
Design Kit and Component Overview page content update for April release

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#390]
> As an IBM.com Library adopter, 

> I need to see the latest information about the design kit and expressive themes

> so that I know how to download the Design Kit properly and use the correct resource.

#### Additional information

Based on the current expressive theme situation, we need to identify content around [design kit](https://ibm-dotcom-library.mybluemix.net/getting-started/designing) and [component overview page](https://ibm-dotcom-library.mybluemix.net/components) that need an update to meet the deadline of April 24th release date.

#### Tasks

- [ ] The First audit is done by Olivia, Jacob, and Jenny
- [ ] Meet to align on the changes/to-dos
- [ ] Create updates content for the live website update

#### Acceptance criteria
- [ ] Content is updated on the live website before April 24th.

**Comment by JennySanchez** [comment]
Discussion session scheduled for April 15, Wednesday, at 10:30 am CST.

**Comment by oliviaflory** [comment]
## *WIP not ready for update* Component overview page

### Upcoming components

*Descriptions remain the same*

| Name & link to storybook | Status |
|---|---|
| [Expressive modal](https://ibmdotcom-react.mybluemix.net/?path=/story/components-expressive-modal--default) | Stable |
| [Horizontal rule](https://ibmdotcom-react.mybluemix.net/?path=/story/components-horizontalrule--default) | Stable |
| [Link with icon](https://ibmdotcom-react.mybluemix.net/?path=/story/components-link-with-icon--default) | Needs updates ? |
| Lightbox media viewer | Under construction |
| [Locale selector](https://ibmdotcom-react.mybluemix.net/?path=/story/components-locale-modal--default) | Stable ? |
| Locale selector notification | Under construction|
| [Table of contents](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-sub-patterns-table-of-contents--manually-define-menu-items) | Stable | 

*New*
| Name & link to storybook | Status |
|---|---|
| [Video player]() | Stable |
| [Image](https://ibmdotcom-react.mybluemix.net/?path=/story/components-image--default) | Stable |
| [Image with caption](https://ibmdotcom-react.mybluemix.net/?path=/story/components-imagewithcaption--default) | Stable |

**Comment by oliviaflory** [comment]
**Image with caption**
The Image with caption component is used to embed images and has an optional caption. It can support images at 1x1, 2x1, 4x3 and 16x9 aspect ratios. 

**Video player**
The Video Player component plays embedded videos using the Kaltura video platform. It can be used in inline patterns as well as modals. It is always the full width of its containing element and maintains an aspect ratio of 16:9.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc We are good to go for the Upcoming Components list update.

**Comment by jacobottesen-dgc** [comment]
All the updates above have been made to the component overview page.

**Comment by JennySanchez** [comment]
Updates completed. Thank you both for the hard work @oliviaflory and @jacobottesen-dgc !
