### ISSUE TITLE
Update Getting Started/Overview page content update for April release

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#396]
@JennySanchez commented on [Tue Apr 14 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2087)

> As an IBM.com Library adopter, 

> I need to see the latest information about the adoption routes and adoption resources (adopter starter kit)

> so that I know how to adapt properly and use the correct resource.

#### Additional information

Since we are open the website content to all IBMers, we need to take a look at the Getting Started/Overview page content and make the proper update.

#### Tasks

- [x] The First audit is done by the leadership team (Linda, Wonil, and Jeff)
- [x] Meet with Jenny to align on the changes/to-dos
- [x] Create updates content for the live website update

#### Acceptance criteria
- [x] Content is updated on the live website before April 24th.

---

@JennySanchez commented on [Tue Apr 14 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2087#issuecomment-613657302)

@wonilsuhibm Task issue created as discussed.

**Comment by JennySanchez** [comment]
**Task Update:** Meeting scheduled for us to go over the current overview page and create a list of necessary changes today.

**Comment by JennySanchez** [comment]
Updates completed.
