### ISSUE TITLE
Cupcake website page content update - Help/FAQ page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#41]
#### User Story

> As an IBM.com page creator

> I need to: know where to find the answers for the most asked questions

> so that I can: get help efficiently.

#### Additional information
- The FAQ page on the Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/help/faq).
- The FAQ page on the current v19a website can be viewed [here](https://www.ibm.com/standards/web/faq.html).
- We need to do adopter research to see what questions our adopters have for the Cupcake website. This task also might be for v1.1 instead of v1.0.

#### Task
- Collaborate with Wonil for the content creation.

#### Acceptance criteria
- [ ] Content and design published with markdowns.
- [ ] Content and design reviewed with Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
**Note:** What is the difference between Component and Pattern?
