### ISSUE TITLE
Review white theme Homepage design documents with the developer

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#429]
@JennySanchez commented on [Thu Apr 23 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2180)

This task is created to review the white theme homepage redesign and redesign the comparison outcome study with the developer who will work on the #381, #382, #383, #384, and #385. So the developer can start the tasks assigned.

[Homepage Redesign Comparison Study](https://user-images.githubusercontent.com/45213839/79917267-c85a3980-83ef-11ea-9eb5-a8b3eea78387.jpg)

#### Task
- [x] Review the Homepage design - desktop, tablet, and mobile view designs #460 .
- [x] Review the outcome (see image below) of [#380](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library-website/380) 

#### Acceptance criteria
- [x] Developer is ready to work on #381, #382, #383, #384, and #385.

**Comment by JennySanchez** [comment]
@jeffchew Let me know who I should review the comparison outcome with and I will set it up asap. Thanks.

**Comment by JennySanchez** [comment]
**Note:** Review session set up for Mon 05/11/2020.

**Comment by JennySanchez** [comment]
@annawen1 The documents we went over today can be found in the website BOX folder [here](https://ibm.box.com/s/q382koq3ottkl7x8lfganuy3bfahzxbr). Please feel free to reach out if you have any further questions whenever you need.
