### ISSUE TITLE
Create the images for the White Theme homepage design

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#467]
The images we need are the image for the hero and Get Started sections (see mockup references below).
![Screen Shot 2020-05-19 at 12 27 28 PM](https://user-images.githubusercontent.com/45213839/82358443-23ba2000-99cc-11ea-9dc0-a748422d11f5.png)

The Slack pictogram is not included in the Carbon Library so we need to create one.
![Screen Shot 2020-05-29 at 8 35 38 PM](https://user-images.githubusercontent.com/45213839/83316556-12eb8480-a1ec-11ea-8438-16f9a7cd8618.png)

#### Task
- [x] Go over the image concept and idea with Wonil to confirm the creative direction
- [x] Create or refine the images
- [x] Review the images with Wonil and Linda for edits if needed, if not, for approval.

#### Acceptance criteria
- [x] Images are finalized and to be prepared for dev implementation.

**Comment by JennySanchez** [comment]
@annawen1 FYI on this task is in place for us to track the image creation process.

**Comment by JennySanchez** [comment]
#### Note

- Hero image
(desktop) 2095 px by 749 px
(tablet) 610 px by 218 px
(mobile) 286 px by 189 px

- Illustration for the "Get Started" section.
(desktop) 287 px by 230 px
(tablet) 208 px by 171 px
(mobile) 287 px by 230 px

- Pictogram for the "Join Slack community" in the "Latest updates" section.
The pictogram stroke needs to be thinner

**Comment by wonilsuhibm** [comment]
@JennySanchez should we just use Slack logo instead?

**Comment by JennySanchez** [comment]
@wonilsuhibm As mentioned, we tried the logo from Slack but it looks too heavy.

**Comment by wonilsuhibm** [comment]
Ah, okay. Can you share here please?

**Comment by JennySanchez** [comment]
![Desktop 1312 - with pictogram](https://user-images.githubusercontent.com/45213839/83537436-292e6480-a4ba-11ea-845a-a5e4e2b4eebf.jpg)
![Desktop 1312 - with Black Slack logo](https://user-images.githubusercontent.com/45213839/83537439-2a5f9180-a4ba-11ea-96e7-41e88dfb52a8.jpg)
![Desktop 1312 - with Color Slack logo](https://user-images.githubusercontent.com/45213839/83537448-2b90be80-a4ba-11ea-924b-eb16e4cf6bdc.jpg)

**Comment by wonilsuhibm** [comment]
@JennySanchez thank you. I see. Do you think we can make the logo smaller?

<img width="931" alt="Screen Shot 2020-06-02 at 11 42 13 AM" src="https://user-images.githubusercontent.com/30183447/83540370-36515080-a4c6-11ea-8b0b-00fea026a1e9.png">

**Comment by wonilsuhibm** [comment]
Or use the same smaller size for all?

**Comment by JennySanchez** [comment]
Hi @wonilsuhibm. I'd like to keep the pictograms the same size and not use smaller icons like the ones in the"Other resource" section. Mainly bc the pictogram is what used in the  Carbon Feature Card set up, it helps differentiate the "Latest Update" section from the "Other resource" section and adds visual hierarchy for the bottom section of the homepage.

Below is what Anna currently has and the Slack pictogram looks pretty close to the other two and looks more like a set now. My recommendation is to move forward with the original pictogram treatment.

<img width="1565" alt="Screen Shot 2020-06-02 at 10 51 06 AM" src="https://user-images.githubusercontent.com/45213839/83542519-aeb51300-a4c0-11ea-84b6-494291557051.png">

**Comment by JennySanchez** [comment]
@wonilsuhibm Here are the homepage hero image explorations, please let me know if either one of them works better, especially taking the illustration you are creating into account. 

Also, if there are any other IBM.com work images or resources you can share with me to mock up a few more options, please send them my way.

---
A. Mocked up with the Lead Space example image.
![Screen Shot 2020-06-02 at 4 54 28 PM](https://user-images.githubusercontent.com/45213839/83574400-0a988f80-a4f3-11ea-949c-ddc444472d39.png)

B. Mocked up with the Lead Space example image.
![Screen Shot 2020-06-02 at 4 54 13 PM](https://user-images.githubusercontent.com/45213839/83574476-2d2aa880-a4f3-11ea-8e80-8d45988dbdb9.png)

C. Mocked up with the Solution page from Lila.
![Screen Shot 2020-06-02 at 4 53 56 PM](https://user-images.githubusercontent.com/45213839/83574523-403d7880-a4f3-11ea-9d65-905e5608d504.png)

D. Mocked up with the [IBM Analytics](https://www.ibm.com/analytics) webpage screenshot.
![Screen Shot 2020-06-02 at 4 53 36 PM](https://user-images.githubusercontent.com/45213839/83574551-53504880-a4f3-11ea-8426-c3360633d102.png)

E. Mocked up with the [IBM Watson](https://www.ibm.com/watson) webpage screenshot.
![Screen Shot 2020-06-02 at 4 53 14 PM](https://user-images.githubusercontent.com/45213839/83574701-9b6f6b00-a4f3-11ea-95bf-614194720a95.png)

**Comment by wonilsuhibm** [comment]
@JennySanchez Thank you. I like the image used in A and B, and the copy from B as it's more generic, but set in A style as it's clearly differentiated from Carbon.

Comment for the lead space copy: I wonder if **efficiently** and **effectively** are the right focus or **IBM.com is a platform** is the right focus, as it's a new concept and lens to look at IBM.com, as opposed to IBM.com as a web site.

**Comment by wonilsuhibm** [comment]
@JennySanchez here are the illustrations I have so far:

### Concept 1: enabling makers
![Desktop 1312 - with hero message in ten-column width Copy 2](https://user-images.githubusercontent.com/30183447/83773721-e3f16a80-a652-11ea-98c9-b1f32131ad92.jpg)

### Concept 2: create & make

##### 2a
![Desktop 1312 - with hero message in ten-column width Copy 7](https://user-images.githubusercontent.com/30183447/83773852-0e432800-a653-11ea-8bc0-79432c23e469.jpg)

##### 2b
![Desktop 1312 - with hero message in ten-column width Copy 5](https://user-images.githubusercontent.com/30183447/83773873-1307dc00-a653-11ea-9a46-d3026d8f05b0.jpg)

##### 2c
![Desktop 1312 - with hero message in ten-column width Copy 4](https://user-images.githubusercontent.com/30183447/83773898-19965380-a653-11ea-9c8e-d281734b6ff4.jpg)

##### 2d
![Desktop 1312 - with hero message in ten-column width Copy 3](https://user-images.githubusercontent.com/30183447/83773917-1ef39e00-a653-11ea-8868-fc2e65a4f885.jpg)

Let me know what you think.

**Comment by wonilsuhibm** [comment]
An update based on Illustration guild feedbacks.

![Artboard 26 copy@4x](https://user-images.githubusercontent.com/30183447/83892659-f59f4480-a71c-11ea-93ed-a2bd07a6528e.png)

![Desktop 1312 - with hero message in ten-column width Copy 2](https://user-images.githubusercontent.com/30183447/83892887-41ea8480-a71d-11ea-891a-525e92a09964.jpg)

**Comment by wonilsuhibm** [comment]
And the final for the conceptual version:
![Artboard 19 copy 4@4x](https://user-images.githubusercontent.com/30183447/83899837-18365b00-a727-11ea-81df-f7ea7d27f8c2.png)

![Desktop 1312 - with hero message in ten-column width Copy 8](https://user-images.githubusercontent.com/30183447/83899844-1b314b80-a727-11ea-9e93-75fc342b9d75.jpg)

**Comment by JennySanchez** [comment]
**Based on the design critique, for the revision:**

- Take another look at the hero message and see if efficiently and effectively are the right focus or IBM.com is a platform is a right focus, as it's a new concept and lens to look at IBM.com, as opposed to IBM.com as a web site.
- Update the hero image with the most up to date iMac image.
- Maybe try a different image for the hero image since the image was heavily used for the lead space examples.
- Maybe try a mobile view of the hero image for the mobile hero image set up.
- The team agreed the darker background image works better.
- The team likes the illustration for both figure and shape concepts.

**Comment by JennySanchez** [comment]
@ljcarot You can view all the Hero Images and illustrations options above and the feedback from the designers for the next step right above this comment. Please let me know if you have any questions and look forward to hearing your thoughts.

**Comment by JennySanchez** [comment]
WIP Leads Space explorations.
![Screen Shot 2020-06-11 at 8.40.12 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/b58340d5-ab30-45db-b30c-f78c3a14012a)

**Comment by ljcarot** [comment]
I like the image 7 - 'Accelerate your business solutions'  with the drone and I like the illustration with shapes.  Can we see them together in a very rough mockup of the homepage with this as copy for hero:  "Our vision is that every visitor on IBM.com has a productive, efficient and delightful experience." 
and this for copy for get started: "We have prepared a set of building blocks, tools and guidelines to help you to make this shared vision a reality."?

**Comment by JennySanchez** [comment]
Thank you @ljcarot and @wonilsuhibm for the feedback. Based on the discussed I had with both of you, below is the latest design and copy for the hero and get started sections. Please let me if there are any edits needed before I prepare the image files for implementation.

![Screen Shot 2020-06-12 at 3.46.14 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/12c73c47-d04a-4de8-bfcc-f2980e68a2b7)

![Screen Shot 2020-06-12 at 3.45.59 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/79898048-6c92-4741-8d90-f4b864c4f907)

**Comment by wonilsuhibm** [comment]
@JennySanchez looks great! Hey, do you think you can move the image a bit higher so that we can see the hands?

**Comment by JennySanchez** [comment]
@wonilsuhibm Good call. Image updated - see above.

**Comment by ljcarot** [comment]
Love it!

**Comment by ljcarot** [comment]
As I read the copy, I think it should say "to IBM.com" instead of "on IBM.com"...do you agree @JennySanchez

**Comment by ljcarot** [comment]
Other than that, it looks good to go!

**Comment by JennySanchez** [comment]
@ljcarot Hero message updated.
![Screen Shot 2020-06-15 at 2.12.42 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/776f8d4f-3ed4-4801-a663-8fd5076708aa)

**Comment by ljcarot** [comment]
Thank you!
