### ISSUE TITLE
White Theme homepage QA fixes before release

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#477]
#### Objective
Make sure all the detail are done and ready for the release.
The PR for fixing can be viewed  [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/472).

#### Task items
- [x] Update homepage hero message per Linda's request and detail can be viewed [here](https://ibm.box.com/s/ml926b2mz7q77zt9chd3c3hznikmz88t)
- [x] Set max-width to the Hero Message so it always stays with a minimum of three lines of text.
- [x] Pictograms are not showing properly when viewed in Safari.
<img width="1039" alt="screen_shot_2020-06-23_at_2 00 42_pm" src="https://user-images.githubusercontent.com/45213839/85448143-0264ca80-b55c-11ea-85c9-36760139f020.png">

- [x] The "Sketch Theme Libraries" card (image one) just goes to the resource page. The link should land on the Theme section (image two) of the page.

(image one) 
![Screen Shot 2020-06-23 at 2 08 45 PM](https://user-images.githubusercontent.com/45213839/85448166-07c21500-b55c-11ea-8e2c-d731dc786fb8.png)

(image two) 
![Screen Shot 2020-06-23 at 2 09 34 PM](https://user-images.githubusercontent.com/45213839/85448261-232d2000-b55c-11ea-8903-b27efafc4a4c.png)

**Comment by ljcarot** [comment]
@JennySanchez When I hover over the link to 'Start contributing' is the internal bluemix url...it be the live url "https://www.ibm.com/standards/web/ibm-dotcom-library/contributions".

**Comment by ljcarot** [comment]
I notice when you use the external link icon, it opens the page in the same window...shouldn't it open in a second window?

**Comment by JennySanchez** [comment]
@ljcarot You are correct, I am not sure why it takes you to the Bluemix URL.

@annawen1 Does it have anything to do with it's in the staging environment? Can we make sure "Start contributing" is linked to https://www.ibm.com/standards/web/ibm-dotcom-library/contributions ?

Thank you.

**Comment by JennySanchez** [comment]
@ljcarot About use the external link icon, I agree on open in a second window is a better experience. However, I noticed the Carbon website has the same treatment and now I wonder if it's a Gatsby Theme card or external link treatment. 

For example, all the cards in the Resource page open within the same window.
View cards on Carbon website Resource page [here](https://www.carbondesignsystem.com/resources/).

**Comment by ljcarot** [comment]
Ok @JennySanchez we can leave that alone for now.

**Comment by JennySanchez** [comment]
@ljcarot Did some investigation and noticed our current homepage the 'Start contributing' is linked to the internal bluemix url as well. My guess is the link did not get updated when we update the URL for some reason - FYI.

**Comment by annawen1** [comment]
@ljcarot @JennySanchez I'll update the "Start contributing" link and make it relative like you suggested. I also tried setting the resource cards to open to a new tab and that works. I push those updates up

**Comment by JennySanchez** [comment]
@annawen1 

**Question:** In the [PR](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/472), I noticed there are conflicts. Just wanna bring it to your attention and make sure it won't be a problem when we push the homepage live as soon as Linda gives the green light.![Screen Shot 2020-06-24 at 3.37.29 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/be2972b6-7a4d-49c8-b095-fd869937e6db)

**Comment by annawen1** [comment]
> @annawen1 The updates look good. Thank you!
> 
> **Question:** In the [PR](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/472), I noticed there are conflicts. Just wanna bring it to your attention and make sure it won't be a problem when we push the homepage live as soon as Linda gives the green light.
> 
> ![Screen Shot 2020-06-24 at 3.37.29 PM.png](https://camo.githubusercontent.com/0ae38d622f94486e0e266e7f192755ea3173957a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564613064623061396630613935303030313466353362662f62653239373262362d376134642d343963382d623039352d666438363939333765366462)

@JennySanchez Yep I noticed, conflicts have been resolved.

**Comment by JennySanchez** [comment]
@annawen1 Awesome. Thanks!

@ljcarot FYI - 'Start contributing' link on the current website is updated.
https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/481

**Comment by JennySanchez** [comment]
@ljcarot @jeffchew @wonilsuhibm All fixes completed and just need to know when you think we should push the update live. Thank you.

**Comment by ljcarot** [comment]
Let’s not wait any longer. I’m good to push live

**Comment by JennySanchez** [comment]
**Update:** Based on the Slack conversation with Anna and Jeff, we got the green light from Jeff. We will push the update live today.

**Comment by JennySanchez** [comment]
White Theme Homepage is updated and [lived](https://www.ibm.com/standards/web/ibm-dotcom-library/).
