### ISSUE TITLE
Expressive Theme release information content crafting

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#490]
> As an IBM.com Library website adopter 

> I need a way to know what is included in the Expressive Theme and where to download it

> so that I can start adopting the theme for my work right away

#### Additional information
- The expressive theme will be available to adopters and will be rolling out in the [ibm.com Library v1.9.0 release](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2220).  
- We need to have the information about the Expressive Theme published on the website once it's ready.

#### Tasks

- [ ] Craft expressive theme release information
- [ ] Review the content with @jeffchew and @oliviaflory 
- [ ] Finalize the content

#### Acceptance criteria
- [ ] Have the finalized content ready for Jenny to publish on the Cupcake website

**Comment by JennySanchez** [comment]
**FYI:** @RobertaJHahn Task issue created and moved to To-Do This Sprint for Sprint 20-13 with the "Sprint must have" labeled as discussed.

**Comment by JennySanchez** [comment]
Hi @annawen1, How's the content crafting goes? Do you need anything?

**Comment by annawen1** [comment]
I'm going to go through @jeffchew's write up and see if anything needs to be added

https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/501/guidelines/expressive-theme
