### ISSUE TITLE
Content publishing - Expressive theme proxy

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#495]
#### Objective

We need to surf the Expressive theme proxy information on the website so IBM.com Library adopters know how to adopter.

#### Tasks

- [ ] Review the finalized content with Olivia via #494
- [ ] Publish the content via markdowns to the website.

### Acceptance criteria

- [ ] Expressive theme proxy information is published and live on the Cupcake website.

**Comment by JennySanchez** [comment]
#495 is done and the content is published. This task issue is no longer relevant.
