### ISSUE TITLE
Update website IA - merging Layout Pattern website pages into Components

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#497]
#### Objective

We need to update the Cupcake website navigation and overview pages to reflect the patterns organization work outcome, so adopters can find what they need on the website properly.

#### Tasks

- [x] Lara to review the final organization with Jenny, Oliva, and Wonil.
- [x] Crafting the description/definitions of the **UI components** and **Layout components**.
- [ ] Update Components overview page content and add the definitions of the **UI components** and **Layout components**.
- [ ] Update Components list table linking and organization.
- [ ] Add tabs to the overview page(**Overview tab** and **Thumbnails tab**).
- [ ] Add the thumbnail illustrations to the thumbnail tab page.
- [ ] Move proper information from the Layout Patterns overview page to be under the Guideline section.
- [ ] Update the website IA (Coding)

**NOTE:** 

- When the "Layout patterns" website pages moved into the "Components" section, we will dim the "Pattern" category label on the left nav until the new Pattern overview content is crafted and ready to be published. After that, we will continually add the MVP patterns content to the "Patterns" category when it's ready to be published.

- When we are ready to move the website pages, what is currently in the Layout Patterns overview page will be hidden until it's updated and ready to be moved under the Guideline section as Page Layout Guideline.

### Acceptance criteria

- [ ] The website IA is updated and live on the website.
- [ ] The components overview page content is updated and live on the website.
- [ ] The Patterns overview page and MVP patterns are agreed on and have timeline for publishing to website.

**Comment by JennySanchez** [comment]
@larahanlon2 This task is to move approved items into the Components section from the current Layout Patterns section - FYI.

**Comment by larahanlon2** [comment]
This looks great. The only additional note is that for the new Patterns, we (Wonil, Jenny and I) agreed that we could leave the Patterns section (nav and overview page) off the website until we have at least the overview page and 1–3 MVP patterns ready to publish. I will write some stories on the board for the patterns work based on our last conversation but I'm thinking the acceptance criteria in this issue but need a slight update so that we're not blocked from updating all the components IA/content before patterns. 

**Suggested edit for acceptance criteria:**
- [ ] The website IA is updated and live on the website.
- [ ] The components overview page content is updated and live on the website.
- [ ] The Patterns overview page and MVP patterns are agreed on and have timeline for publishing to website.

**Comment by JennySanchez** [comment]
@larahanlon2 Sounds good and acceptance criteria are updated. 
Whenever you create task stories for the "Patterns" overview content crafting work, can you link them to this EPIC, please?

**Comment by JennySanchez** [comment]
@larahanlon2 This has been a wonderful collaboration experience and journey for us. Thank you for your contribution and hard work!
