### ISSUE TITLE
Finalize Layout Patterns thumbnail illustrations

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library-website#524]
### Tasks
- [x] Review the images with Wonil and Linda for feedback via issue: carbon-design-system/ibm-dotcom-library#488
- [x] Make changes as needed.
- [x] Finalize wireframes images. 

### Acceptance criteria
- [x] Images are ready for publishing.

**Comment by JennySanchez** [comment]
Jacob and I shared the wireframe images in the DGC Design Critique and the feedback from the designers can be viewed [here](https://ibm.box.com/s/ba4p4j0eclo7i5avz5kp8ubemijtas39).

**Comment by jacobottesen-dgc** [comment]
Meeting schedule with Linda & Wonil on 24th.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Once the images are ready, please share the link to the images here. Thank you.

**Comment by jacobottesen-dgc** [comment]
Wonil is currently reviewing the patterns thumbnails in box: https://ibm.box.com/s/he8ralj1i0u9siwdijxwstya30cppgxi

**Comment by jacobottesen-dgc** [comment]
Images exported and uploaded to Box: https://ibm.box.com/s/hx2xg8kp7hardtzjstgypcda3qjzcccd
