### ISSUE TITLE
Update Layout Patterns naming for the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#528]
#### Objective

To make sure the pattern naming and descriptions match across the website left navigation, the Layout Pattern overview page list.

#### Task

- [x] Audit pattern naming in both areas
- [x] Share the audit with the team
- [x] Finalize the naming
- [x] Update the nav and list on the website

#### Acceptance criteria

- [x] Naming on consistent across the website.
- [ ] ~Make sure there's a task issue for the Dev team to work on the Storybook pattern naming and description updates.~

**Comment by JennySanchez** [comment]
All website left navigation and the overview page list is up to date and followed the [Airtable inventory list](https://airtable.com/invite/l?inviteId=invrvCXWsvWcZgUY9&inviteToken=b65bc895637b62ee48e4a4422d30e1c636aaee7f81d4af63882daaac27d0a114).
