### ISSUE TITLE
(Cupcake Website) Tile view implementation for the Components overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#541]
### The Components overview page has UI Components and Layout Components.

---

> As an IBM.com library adopter (designer and none designers), 
> I need to see an inventory of the Layout Patterns not only in the list view but also the image view, 
> so I can quickly find what IBM.com Library offers based on my preferences.

#### Note
- The code can be copied from the Carbon Component Overview page:  https://carbondesignsystem.com/components/overview/
- https://github.com/carbon-design-system/carbon-website/tree/master/src/components/ComponentOverview
- Jacob will export all of the images for the tiles as an svg and save in the [Final SVGs BOX folder.](https://ibm.box.com/s/8y9cxrfvi2uc63o15i1qqpmvf1muaf2v).
- The page will include separate sections for the UI Components and Layout Components.  The same as the existing List View om the [component Overview page](https://www.ibm.com/standards/web/ibm-dotcom-library/components).

### Tasks

- [x] Go over the task detail and kick off with Jenny.
- [ ] Implement the tile set up with the wireframe images Jacob created (#524) to the Layout Patterns overview page with code.
- [ ] Share the preview link with Jenny for QA.
- [ ] Merge PR for the tile view to go live on the Cupcake Website.

### Acceptance criteria
- [ ] All Components and Layout Patterns are presented in the Tile view live on the cupcake website.

**Comment by JennySanchez** [comment]
@RobertaJHahn It will be ideal for this to be done by Sprint 20-16, if not, Sprint 20-17.

**FYI:** @ljcarot @wonilsuhibm

**Comment by JennySanchez** [comment]
**Note:** The spacing in between the Cards need attention to make sure they work properly.

**Comment by jacobottesen-dgc** [comment]
I worked on adding images and tiles in this PR. You can view the updates on the gallery tab on the pattern page.

https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/537

**Comment by JennySanchez** [comment]
@RobertaJHahn Wonil provides more feedback and guidance for Jacob to work on the tile illustrations. We need to finalize the illustration before the developer can start on this task. For now, let's take the Sprint 20-16 setting off and move this task issue to the backlog until the tile illustration is finalized, please. Thank you.

**Comment by JennySanchez** [comment]
**Task update:**
The website stream is working on a few image updates with the Carbon Team and will provide the final SVGs as soon as we can. Please contact Jenny before you start the task to make sure all images are ready to go.

**Comment by jeffchew** [comment]
@RobertaJHahn fyi, I'm bumping this to a 5 as I'm looking more closely at all of the work involved.

**Comment by JennySanchez** [comment]
@jeffchew 
Jacob helped with the SVG image exporting and the images can be found [here](https://ibm.box.com/s/8y9cxrfvi2uc63o15i1qqpmvf1muaf2v).
The Sketch work file from Carbon can be found in the [same folder](https://ibm.box.com/s/u8xdfifscju6bjbjm10xgx4zm0svdton) as well, in case anyone needs it.

Let me know if you need anything else. Thank you.
