### ISSUE TITLE
Finalize Components thumbnail illustrations

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#544]
@JennySanchez commented on [Mon Jul 27 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3288)

### Tasks
- [x] Review the images with Wonil and Linda for feedback
- [x] Make changes as needed.
- [ ] Finalize wireframes images. 

### Acceptance criteria
- [ ] Images are ready for dev implementation.

All wireframes can be viewed here: https://ibm.ent.box.com/folder/118968988056

**Comment by jacobottesen-dgc** [comment]
Component thumbnails images exported and uploaded to Box: https://ibm.box.com/s/hx2xg8kp7hardtzjstgypcda3qjzcccd
