### ISSUE TITLE
Adopter Kit release

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#610]
(Planning detail can be viewed on the [ideation board](https://github.com/carbon-design-system/digital-design-ideation/issues/64))

> As an IBM.com Library early adopter,

> I need a way to find out information and get access to the Adopter Kit DDS team offers,

> So that I can adapt to IBM.com's Library as fast as I can.

#### Task

- [x] Create an Adopter Kit access request Git template.
- [ ] Add a section in the Get Started Overview page and provide a link to Git for adopter kit access requests. 
- [ ] Add a card to the "Resource" section and link to Git for adopter kit access requests.
- [ ] Announcement made in the digital-design-squad and other proper Slack channels.
(ex: IBM-digital-design and digital-design-system Slack channels by Linda)

#### Acceptance criteria
- [ ] All three tasks listed above are completed and content is on the live website.

**Comment by JennySanchez** [comment]
@wonilsuhibm This is based on the "Design kit access request" Git template (see below) we currently use. Please let me know what do you think about the content for the Adoprer Kit below the image, especially the areas I highlighted in gray.

![Screen Shot 2020-08-20 at 1 22 01 PM](https://user-images.githubusercontent.com/45213839/90810376-79aea480-e2e8-11ea-871d-c218586384e5.png)


---


**Template title:** 
Design kit access request

**Template content:**

Thanks for your interest in the `IBM.com Adopter Kit`!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from `Carbon for IBM.com` will reach out to you soon regarding your request for access.

> What is your email address?


> Which team are you on?


> What experience are you designing for?


> What platform is your experience on? (ie. Drupal, Wordpress, etc)


> Please list a point of contact for:
Offering manager
Design lead
Development lead


> Please share any additional information you'd like to share about your project?

**Comment by wonilsuhibm** [comment]
Other than the title, this sounds good. Thank you.

**Comment by JennySanchez** [comment]
@wonilsuhibm My apology for miss the title and it's updated now. I also want to make sure the name for the kit is "Early Adopter Kit". Can you confirm?

**Comment by jacobottesen-dgc** [comment]
cc. @wonilsuhibm @JennySanchez 

Here is the proposed content for the adopters starter kit section of the getting started page. 

We have created an adopters starter kit to provide you with upcoming guidelines, important IBM Design sites, and IBM.com sketch assets. At the moment, this kit is a work in progress. Please request access here  and we will continue to add to it as we produce more guidelines and resources.

Feedback/thoughts?

**Comment by JennySanchez** [comment]
@jacobottesen-dgc , 
A reminder for the two items we talked about last Friday.

- Section title
- A link for the Git access request.

**Comment by jeffchew** [comment]
Template has been updated: https://github.com/carbon-design-system/ibm-dotcom-library-design-kit/issues/new/choose

**Comment by JennySanchez** [comment]
@jeffchew As mentioned in the Slack conversation, the template looks great but we need to move it from the Design Kit repo to our team repo. 🙏

**Comment by JennySanchez** [comment]
**FYI:** 
@jacobottesen-dgc There are directional changes to this task, detail will be coming soon. 
@RobertaJHahn Can we move this task to Sprint 20-19 so we can continue the work, please.

**Comment by JennySanchez** [comment]
**Task follow-up:** Add the Adtoper Kit discussion to the Thursday team huddle session for further discussion as a team and align on the next step.

**Comment by JennySanchez** [comment]
Based on the conversation we had in the Team Huddle today, we will move forward with:

- Rename the folder in our team box folder to be the Experimental Design Asset folder.
- Not mention or promote the asset on our website nor adding access requests on the website but rather share the assets as needed with our adopters.
