### ISSUE TITLE
Update Sketch MVP content publishing template 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#613]
#### Objective:

We went through a few runs of the MVP content publishing template while worked on the Layout Patterns and Components section content publishing. We need to take the feedback and update the template to make sure we capture all the updates.

#### Tasks:

- [x] Update the Sketch template to be true to the discission outcome on publishing the Slack channel.
- [ ] Review template with Wonil to make sure he is aligned on the updates.
- [ ] Upload the new template to the BOX folder.
- [ ] Let DDS team members know where to find it and what has been updated.

### Acceptance criteria
- [ ] The Sketch MVP content template is updated and ready for the DDS team members to use.

**Comment by sethibm** [comment]
@JennySanchez @wonilsuhibm Can take a look at this file and confirm if it captures the latest?  

https://ibm.box.com/s/v7bnbm89kwhbzv7czn4b9od1c6e33o7z

Updated MVP Sketch file for the both Layout Components and Components with Use Case.  Changes:
- Added Component with use case specs, making use of new 608px image size
- Added documentation for links within design

It's currently in work in progress but should be moved asap to main folder, once finalized and approved, per above checklist.

Fyi, there are some differences in component presentation, and decision on whether to show it as 928px or 608px, and whether to pick white or grey background, that is not yet documented or explained in this document.  See the Locale modal:

https://www.ibm.com/standards/web/ibm-dotcom-library/components/localemodal

It may help to make a new task, or assign someone else to handle this task and next update to MVP file.

**Comment by JennySanchez** [comment]
@sethibm Looking good and I will work on the rest. Thank you again for your contribution to the website publishing and template updates. I will reach out with questions next week if it's ok with you.

**Comment by JennySanchez** [comment]
Template related work will be share in the Monday demo and continually live as a living document for iterations.
