### ISSUE TITLE
Content crafting for the updated Components Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#614]
#### Objective:
Since we are moving website pages from Layout patterns section into the Components section, we need to update Components overview page content to reflect the changes and add the definitions of the UI components and Layout components sections, so adopters know what are the differences between them.

#### Tasks:

- [x] Work on the purposed content and review with Wonil, Olivia, and Lara.
- [x] Finalize the content

### Acceptance criteria

- [x] Content is finalized and ready for markdown update.

**Comment by JennySanchez** [comment]
@larahanlon2 @oliviaflory @wonilsuhibm 

I set up a BOX document for the content update work and can be viewed [here](
https://ibm.box.com/s/h7ep6i9rld5kibf97rdd0pejol7y33g1).

**Comment by larahanlon2** [comment]
Thank you @JennySanchez !! I left 2 comments inline. Here are some other early descriptions I wrote when I was working on the future-state prototypes.

—

**UI components**
Components that are designed and built to support or enable small UI tasks and actions. They can be used with other design system components to create layout components, templates, and patterns.

**Layout components [option 1]**
Layout components show some of the common layouts used in IBM’s digital space. They are carefully designed and coded to communicate prescribed content types and are expressions of IBM’s distinct brand ethos.

**Layout components [option 2]**
Coded UI pieces that use multiple components and elements to build complex editorial layouts. These can be reused to create patterns that serve different purposes.

**Comment by JennySanchez** [comment]
@larahanlon2 Nice! I like the layout components options 2, bc it's very easy to understand and pair well with the UI components description. Thoughts, @wonilsuhibm and @oliviaflory ?

**Comment by wonilsuhibm** [comment]
@larahanlon2 @JennySanchez thank you. overall sounds good. Some minor comments:

Under UI components, the part that says "They can be used with other design system components...", the "design system components" part sounds slightly weird. Can you use it with your own custom components as well?

Under UI components, the part that says "to create layout components, templates and patterns", should we add "other components" to the mix? -> "to create other components, templates, and patterns"

Of the two layout component options, I lean towards option 1. The differentiation between UI components and layout components feels better defined with option 1.

**Comment by oliviaflory** [comment]
IMO we don't have to call out "custom components" specifically, @larahanlon2 would changing "used" to "paired" and removing "design system" per Wonil's feedback still align with your definition? 

**UI components**
Components that are designed and built to support or enable small UI tasks and actions. They can be paired with other  components to create layout components, templates, and patterns.

---
For layout components...
I like the call out of editorial layouts in option 2, but also agree with Wonil option 1 which might be better

**Comment by larahanlon2** [comment]
@oliviaflory yes, that is much better, thank you!

I also agree that option 1 for layout components might be best because it's the definition we have been using for layout patterns already – in updated direction these are the same thing so I would rather not change or deviate from that too much as it will require another level of education. 

Based on all the comments in this thread, here are the most favored definitions:

**UI components**
Components that are designed and built to support or enable small UI tasks and actions. They can be paired with other components to create layout components, templates, and patterns.

**Layout components**
Layout components show some of the common layouts used in IBM’s digital space. They are carefully designed and coded to communicate prescribed content types and are expressions of IBM’s distinct brand ethos.

@JennySanchez whatcha think?

**Comment by JennySanchez** [comment]
Dig it!!! @larahanlon2

**Comment by JennySanchez** [comment]
@wonilsuhibm Thumbs up for approval, please.

**UI components**
Components that are designed and built to support or enable small UI tasks and actions. They can be paired with other components to create layout components, templates, and patterns.


**Layout components**
Layout components show some of the common layouts used in IBM’s digital space. They are carefully designed and coded to communicate prescribed content types and are expressions of IBM’s distinct brand ethos.
