### ISSUE TITLE
Merge Layout Pattern website pages into Components section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#628]
> As an IBM.com Library components adopter, 
> I need a way to view all the available UI and Layout components on the overview page,
> so that I know which components I need to adopt for my project.

#### Task

- [x] Find out what will be the most efficient way to do the merge.
- [x] Update the navigation labels and make sure they are in alphabetic order
- [x] Add the definition under each section (UI + Layout) #614 
- [x] Update the table List 
- [x] Update the table List links
- [x] Update the image links on website pages

#### Acceptance criteria

- [x] All Layout Pattern website pages on under the Components section on the left navigation.
- [x] UI and Layout components sections are on the Components overview page and live on the website

**Comment by JennySanchez** [comment]
@RobertaJHahn I need to do some research before I can set the Story point for this story - FYI.

**Comment by JennySanchez** [comment]
Set up a discover all with Jeff for today at 3:00 pm CT.

**Comment by JennySanchez** [comment]
@RobertaJHahn FYI: I am collaborating on this task with Jeff and added him to this task issue.

**Comment by JennySanchez** [comment]
**Update:** 

- Left nav and Components overview page table view list and link update completed.
- Layout page added under Guideline section.

PR detail can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/653).

**Next step:** 

- Work on the Layout page (under Guideline section) intro copy update.
- Work on the Patterns overview page content update.

**Comment by JennySanchez** [comment]
The Layout page (under Guideline section) intro copy and the Patterns overview page content update completed - PR merged.

**Comment by JennySanchez** [comment]
Audit and fixing for this task will be recorded via #660.
