### ISSUE TITLE
Dev assistant for Cupcake website page content fix (Sprint 24)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#63]
> As an: Cupcake website content creator

> I need to: fix errors and problems with the assistance of an experienced developer

> so that I can: present the content with the correct layout and feature set up.

#### Additional information
- The items we need to work on together will be recorded below.
- I will schedule a work session for us for the second week of the sprint so we can fix what we worked on the week before.
- We will work on the fix together, so Jacob and I can learn how to troubleshoot.

#### Task
- Will be listed via comment as we go.

#### Acceptance criteria
- [x] Errors and problems fixed and updated on the live website.

**Comment by jacobottesen-dgc** [comment]
@jeffchew I am having some issues with this PR. Could you take a look?
https://github.com/carbon-design-system/carbon-for-ibm-website/pull/162

**Comment by jacobottesen-dgc** [comment]
@jeffchew For this table:

1.) Could you let the tokens stretch all the out so it doesn't have to be two lines?

2.) Could you add the tags styles to this section? Carbon's component status page has examples: https://www.carbondesignsystem.com/components/component-status

![Screen Shot 2019-12-09 at 11.55.09 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/ebf90e01-d9b1-4a3d-9138-b74de2576efa)

**Comment by jacobottesen-dgc** [comment]
@jeffchew 

For this section, could we tighten up the content on the 2 row? The content looks uneven with the rest of the table.

[Uploading... Screen Shot 2019-12-09 at 11.58.45 AM.png ]

**Comment by jacobottesen-dgc** [comment]
@jeffchew For these links on the Leadspace page, can we give them a firewall so only IBMers can see access them?

![Screen Shot 2019-12-09 at 3.58.13 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/ff8cbe22-55c1-403f-9c23-e38996b64ba3)

**Comment by jacobottesen-dgc** [comment]
Hey @jeffchew I am having issues with nest bullet points. Could you help me fix this? The issue is on the lead space page under specs.

![Screen Shot 2019-12-12 at 2.03.20 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/d7146dee-caca-42da-8e59-6172aeeea361)

https://carbon-for-ibmdotcom.netlify.com/patterns/leadspace

**Comment by JennySanchez** [comment]
- [ ] Bullet points in number styling alignment fix:
![Screen Shot 2019-12-16 at 2 58 24 PM](https://user-images.githubusercontent.com/45213839/70942562-8a4da300-2014-11ea-9607-168cdedd2305.png)

**Comment by JennySanchez** [comment]
- [ ] Storybook naming confirmation:

@jeffchew I want to make sure we have consistency with the storybook naming. This is what we currently have for the `Component`(left) and `Pattern`(right).
<img width="784" alt="Screen Shot 2019-12-16 at 1 44 30 PM" src="https://user-images.githubusercontent.com/45213839/70945239-5e352080-201a-11ea-8a66-012be32c521f.png">
---

**Does it make sense to call it:**

A: Carbon for IBM.com Components React Storybook + Carbon for IBM.com Pattern React Storybook

or

B: IBM.com Components React Storybook + IBM.com Pattern React Storybook

**Comment by jacobottesen-dgc** [comment]
@jeffchew I am not sure how to change the icons on the on the homepage. They are formatted differently than cards on our other pages. Could you help out with that?

![Screen Shot 2019-12-16 at 2.49.33 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/f5a350cf-8f86-4e72-b9cc-481fa64b2b5b)

**Comment by jeffchew** [comment]
> @jeffchew For this table:
> 
> 1.) Could you let the tokens stretch all the out so it doesn't have to be two lines?
> 
> 2.) Could you add the tags styles to this section? Carbon's component status page has examples: https://www.carbondesignsystem.com/components/component-status
>

PR opened for this: https://github.com/carbon-design-system/carbon-for-ibm-website/pull/206

**Comment by jeffchew** [comment]
> @jeffchew For these links on the Leadspace page, can we give them a firewall so only IBMers can see access them?
> 
> ![Screen Shot 2019-12-09 at 3.58.13 PM.png](https://camo.githubusercontent.com/cea537144c264b85f372d94660cb242a99581139/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564613565643938333366373435303030313963343939662f66663863626532322d353563312d343033662d396332332d653338393936623634626133)

That will be pretty challenging at the moment, we would need to set that up across all of the netlify outputs and would take some effort. I actually am wondering if this is worth doing, and the netlify outputs are also referenced in the markdown code in the codebase as well so it might confuse people.

**Comment by jeffchew** [comment]
> Hey @jeffchew I am having issues with nest bullet points. Could you help me fix this? The issue is on the lead space page under specs.
>  
> https://carbon-for-ibmdotcom.netlify.com/patterns/leadspace

Pushed up this fix in the same PR: https://github.com/carbon-design-system/carbon-for-ibm-website/pull/206

**Comment by jeffchew** [comment]
> * [ ]  Storybook naming confirmation:
> 
> @jeffchew I want to make sure we have consistency with the storybook naming. This is what we currently have for the `Component`(left) and `Pattern`(right).
> 
> <img alt="Screen Shot 2019-12-16 at 1 44 30 PM" width="784" src="https://user-images.githubusercontent.com/45213839/70945239-5e352080-201a-11ea-8a66-012be32c521f.png">
> 
> ---
> **Does it make sense to call it:**
> 
> A: Carbon for IBM.com Components React Storybook + Carbon for IBM.com Pattern React Storybook
> 
> or
> 
> B: IBM.com Components React Storybook + IBM.com Pattern React Storybook

My vote is for:

- `IBM.com Library Components (React)`
- `IBM.com Library Patterns (React)`

Storybook is already in the heading, so adding storybook would be redundant.

**Comment by jacobottesen-dgc** [comment]
@jeffchew Having issues with lists on the masthead page ![Screen Shot 2019-12-18 at 8.55.09 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/99d9dd90-764e-4e9a-8d42-71cd6767c8de)

**Comment by jeffchew** [comment]
> @jeffchew I am not sure how to change the icons on the on the homepage. They are formatted differently than cards on our other pages. Could you help out with that?
> 

Fixed in this PR: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/214

**Comment by jeffchew** [comment]
> @jeffchew Having issues with lists on the masthead page 

Fixed in PR: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/215

**Comment by JennySanchez** [comment]
- [ ] General spacing fix
(especially below the H2)
![Screen Shot 2019-12-18 at 11 36 26 AM](https://user-images.githubusercontent.com/45213839/71109381-ad9a5e80-218a-11ea-99f4-0d16648c5374.png)

**Comment by jeffchew** [comment]
> * [ ]  Bullet points in number styling alignment fix:

Fixed with PR: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/218

**Comment by JennySanchez** [comment]
- [ ] Table "tag" styling.

@jeffchew I tried to applied the styling to other pages but failed. 

Pages we need to applied the same "tag" styling to:
- https://ibm-dotcom-library.netlify.com/components
- https://ibm-dotcom-library.netlify.com/components/footer
- https://ibm-dotcom-library.netlify.com/components/masthead
- https://ibm-dotcom-library.netlify.com/patterns/leadspace


![Screen Shot 2019-12-19 at 10 59 28 AM](https://user-images.githubusercontent.com/45213839/71192880-b94f5900-224e-11ea-9aea-c1db6b471495.png)

**Comment by JennySanchez** [comment]
👉 Wanna make sure we don't forget #191

**Comment by JennySanchez** [comment]
- [ ] The  "Latest update" section cards should have 16 px spacing in between them.
![Screen Shot 2019-12-19 at 2 42 51 PM](https://user-images.githubusercontent.com/45213839/71208082-e828f780-226d-11ea-8a36-94e12fcdbdac.png)

**Comment by JennySanchez** [comment]
- [ ] Vertical spacing below the list.

What we currently have on the website - too much vertical spacing. 
![Screen Shot 2019-12-19 at 3 06 07 PM](https://user-images.githubusercontent.com/45213839/71210598-dbf36900-2272-11ea-8a9d-253a82f73520.png)


It should only be a line break and looks like this.
![Screen Shot 2019-12-19 at 3 27 30 PM](https://user-images.githubusercontent.com/45213839/71211154-21fcfc80-2274-11ea-8fd1-8df65600f7f5.png)

**Comment by JennySanchez** [comment]
All leftover items in this task issue are consolidated to issue #246. This issue will be closed.
