### ISSUE TITLE
Update images on the Footer website page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#654]
#### User Story

> As an IBM.com Library components adopter, 

> I need to see the latest footer images on the IBM.com Library website 

> so that I can reference the components to my day to day work without confusion.

#### Additional information

The current footer images can be viewed [here](http://ibm-dotcom-library.mybluemix.net/components/footer).

#### Task

- [x] Talk to Wonil and find out where is the footer image work file
- [x] Confirm the areas the updates need to be made
- [x] Prepare the updated images for markdown update
- [x] Make the update on the live website.

#### Acceptance criteria

- [ ] Images are updated and live on the website.

**Comment by JennySanchez** [comment]
Image updates were completed. 

- The new updated images and Sketch work file are saved in the [BOX folder](https://ibm.box.com/s/ks8juuduyzxf67nqrpxmpqy81fi0nsqp).
- The PR detail for the update can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/675).
