### ISSUE TITLE
Dev Fix: The text is cut off in the table list view on the Guideline Overview Page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#663]
#### Problem
The text is cut off in the table section.

![Screen Shot 2020-09-21 at 8.09.16 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/fbbe1dc0-8a6d-4371-bace-175a34b7aaf8)

#### Task

- [x] Research and find out what caused the problem
- [x] Fix the problem and make sure the content display properly

##### Acceptance criteria

- [ ] - [ ] Table content display correctly and properly on the live website.

**Comment by JennySanchez** [comment]
![Screen Shot 2020-09-21 at 10 01 19 AM](https://user-images.githubusercontent.com/45213839/93783798-c3ddbb00-fbf1-11ea-997b-e742a41d6cd7.png)

**Comment by JennySanchez** [comment]
Fixing PR detail can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/662).
